### ISSUE TITLE
fromNarrowBandAngData fails without kwargs

### ISSUE THREAD

**Issue by SebastianSemper** [EMS-TU-Ilmenau/EADF#57] opened 2020-03-11 10:10 UTC
Running

```
import eadf
import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":

    # name of pattern .mat file
    fileNamePattern = "TUI_SPUCA_2x8_I_20MHz_pattern.mat"

    # obtain EADF object
    EADF = eadf.importers.fromNarrowBandAngData(fileNamePattern)
```

I get

```
Traceback (most recent call last):
  File "QR.py", line 33, in <module>
    EADF = eadf.importers.fromNarrowBandAngData(fileNamePattern)
  File "/home/seb/git/Code/EADF/eadf/importers.py", line 397, in fromNarrowBandAngData
    :, :, :, :, arrPorInd
IndexError: index 255 is out of bounds for axis 4 with size 32
```

**Comment by ChristophWWagner** [comment] 2020-03-26 18:33
I would like to help resolving this issue. Unfortunately, I cannot reproduce the error due to missing `TUI_SPUCA_2x8_I_20MHz_pattern.mat` file. Please proide a MWE such that this an be resolved

**Comment by SebastianSemper** [comment] 2020-04-20 13:04
How far are we here?

**Closed** 2020-04-22 16:48 UTC
Labels: bug
